name: Java CI with JUnit

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Run tests
        run: |
          javac -d out src/**/*.java
          java -cp out org.junit.runner.JUnitCore LoginAppTest
